#!/usr/bin/env bash

set +abeuvx

cmd=$1
PROJ_NAME='peg_etl'

display_help() {
    echo "Usage: $0 [option]" >&2
    echo
    echo " Available options:"
    echo "   build           "
    echo "   db              "
    echo "   shell           "
    echo
}

case $cmd in

    '-h')
        display_help
        exit 0
        ;;

    'build')
        docker build -t $PROJ_NAME .
        ;;

    'setup')
        docker volume create peg_etl_db_data
        ;;

    'db')
        docker run -d \
        --name $PROJ_NAME \
        -p 5436:5432 \
        -e POSTGRES_DB=peg_etl \
        -e POSTGRES_USER=peg \
        -e POSTGRES_PASSWORD=africa \
        --mount source=peg_etl_db_data,destination=/var/lib/postgresql/data \
        $PROJ_NAME:latest
        ;;

    'shell')
        docker exec -it $PROJ_NAME /bin/bash
        ;;

     *)
        echo "Unknown command: $cmd"
        display_help
        exit 1
        ;;

esac
