#!/usr/bin/env bash

set +abeuvx

cmd=$1
PROJ_NAME='peg_etl'
DB_NAME='peg_etl'
DB_USER='peg'
DB_PWD='africa'
CTN_ID='8818ba9f2f5b'

display_help() {
    echo "Usage: $0 [option]" >&2
    echo
    echo " Available options:"
    echo "   schema-init           "
    echo "   etl_1_raw             "
    echo "   etl_2_staging         "
    echo "   etl_3_intermediate    "
    echo "   etl_4_finance         "
    echo
}

case $cmd in

    '-h')
        display_help
        exit 0
    ;;

    'schema-init')
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'schema_management/data_raw.sql';
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'schema_management/data_staging.sql';
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'schema_management/data_intermediate.sql';
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'schema_management/etl_4_finance.sql';
    ;;

    'etl_1_raw')
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'etl_1_raw/etl_raw_data.sql';
    ;;

    'etl_2_staging')
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'etl_2_staging/contract.sql';
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'etl_2_staging/customer.sql';
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'etl_2_staging/product.sql';
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'etl_2_staging/transaction_deposit.sql';
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'etl_2_staging/transaction_payment.sql';
    ;;

    'etl_3_intermediate')
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'etl_3_intermediate/contract_start_date.sql';
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'etl_3_intermediate/contract_payment_summary.sql';
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'etl_3_intermediate/contract_projection.sql';
    ;;

    'etl_4_finance')
        docker exec -it $CTN_ID psql -U peg -d peg_etl -f 'etl_4_finance/contract_status.sql';
    ;;

    *)
        echo "Unknown command: $cmd"
        display_help
        exit 1
    ;;

esac

